starting preprocessing luna
026
165
404
784
304
080
760
443
111
440
816
803
426
878
264
059
107
504
335
517
058
243
100
090
066
372
378
351
247
275
086
195
018
255
067
305
550
280
770
828
225
081
538
296
860
668
439
815
379
185
863
250
534
373
743
397
884
346
347
407
720
234
300
263
831
063
436
541
456
583
610
164
411
413
488
746
709
223
561
793
634
686
559
218
122
316
482
020
420
367
128
852
070
123
325
515
013
775
047
435
584
146
599
246
127
095
254
024
751
116
615
568
801
819
273
528
337
648
144
467
031
402
532
312
014
171
302
214
333
861
429
057
360
622
290
193
327
291
546
157
499
159
450
287
498
126
688
163
115
683
216
315
687
713
724
382
314
630
685
252
740
134
010
468
174
867
232
052
495
602
879
113
091
045
714
633
170
796
721
266
787
094
745
105
887
563
112
064
043
580
772
651
624
697
732
587
802
717
150
705
049
701
620
765
307
flip!
826
659
342
781
009
073
282
606
202
643
421
145
613
334
754
684
097
502
001
198
535
570
217
437
866
762
206
592
459
782
087
600
125
748
785
700
392
348
883
188
205
755
597
flip!
142
237
501
181
226
236
676
558
545
818
044
510
791
016
268
235
536
851
244
800
653
767
271
471
399
465
176
102
054
514
865
575
416
674
265
585
799
256
565
027
022
777
173
736
656
810
776
726
453
311
487
607
885
820
096
166
794
766
625
419
276
551
855
604
839
368
415
257
672
853
344
143
flip!
224
flip!
868
353
874
197
154
735
886
004
832
119
458
320
723
768
562
427
395
632
618
015
647
603
470
flip!
876
flip!
531
281
072
692
650
621
297
120
Traceback (most recent call last):
  File "prepare.py", line 376, in <module>
    preprocess_luna()
  File "prepare.py", line 284, in preprocess_luna
    _=pool.map(partial_savenpy_luna,range(N))
  File "/home/wuhui/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/wuhui/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
MemoryError
starting preprocessing luna
026
784
404
860
443
760
165
803
504
081
878
080
304
111
426
770
440
538
264
816
058
090
351
378
517
100
107
372
059
335
550
247
066
067
243
255
018
275
305
086
296
195
828
225
559
456
379
686
314
668
020
439
482
831
584
420
047
347
128
852
413
534
583
373
185
063
300
743
793
316
223
164
250
515
411
397
863
157
720
218
263
610
013
246
146
346
234
402
709
499
688
488
163
123
541
254
648
126
367
467
280
867
775
127
302
435
382
676
116
342
634
815
884
337
568
159
819
360
685
887
174
327
528
291
325
615
315
144
746
450
772
751
532
407
216
429
031
202
273
115
630
312
049
687
421
287
057
014
861
436
713
622
010
801
171
095
498
599
796
073
879
290
122
232
705
683
724
113
565
193
717
714
787
125
495
721
561
091
252
170
307
535
700
070
802
214
064
563
334
266
697
592
643
105
624
633
045
762
732
282
502
416
587
745
866
054
701
613
765
097
510
656
684
546
206
785
748
459
570
044
501
188
094
514
468
597
027
145
754
883
536
659
flip!
826
198
flip!
142
024
009
818
800
620
781
740
865
600
558
606
052
602
767
205
143
791
236
674
348
217
392
087
545
480
755
399
150
736
437
471
453
134
580
653
851
244
465
181
016
256
271
022
470
415
777
176
096
112
551
810
004
607
173
575
001
103
268
276
604
235
320
625
585
311
839
799
479
776
102
631
726
639
820
flip!
224
166
395
353
768
782
flip!
876
766
270
621
562
120
632
647
874
MetaImage: M_ReadElementsData: data not read completely
   ideal = 240123904 : actual = 63166240
072
886
412
344
015
141
483
723
197
833
862
259
657
836
654
277
692
384
669
506
050
199
374
650
729
735
694
794
512
821
419
548
154
293
257
flip!
868
603
689
359
641
012
219
813
043
Traceback (most recent call last):
  File "prepare.py", line 376, in <module>
    preprocess_luna()
  File "prepare.py", line 284, in preprocess_luna
    _=pool.map(partial_savenpy_luna,range(N))
  File "/home/wuhui/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/wuhui/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
MemoryError
007
